"""
Pydantic models for the Infotainment Accessibility Pipeline.
All models use strict typing and JSON serialization.
"""

from typing import Any, Dict, List, Literal, Optional, Union
from uuid import UUID, uuid4
from pydantic import BaseModel, Field


# Type aliases for better readability
Severity = Literal["info", "minor", "moderate", "serious", "critical"]
Confidence = Literal["low", "medium", "high"]


class FileSpan(BaseModel):
    """Represents a span of code in a specific file."""
    file_path: str = Field(..., description="Path to the file")
    start_line: int = Field(..., ge=1, description="Starting line number (1-indexed)")
    end_line: int = Field(..., ge=1, description="Ending line number (1-indexed)")
    code_snippet: str = Field(..., description="The actual code content in this span")
    
    def __post_init__(self):
        if self.end_line < self.start_line:
            raise ValueError("end_line must be >= start_line")


class CandidateIssue(BaseModel):
    """A potential WCAG issue discovered by LLM-1."""
    id: UUID = Field(default_factory=uuid4, description="Unique identifier")
    rule_id: str = Field(..., description="WCAG rule ID (e.g., '1.1.1')")
    title: str = Field(..., description="Brief title of the issue")
    description: str = Field(..., description="Detailed description")
    evidence: List[FileSpan] = Field(..., description="Code spans that support this issue")
    tags: List[str] = Field(default_factory=list, description="Categorization tags")
    llm_model: str = Field(..., description="Model that discovered this issue")
    confidence: Confidence = Field(..., description="Confidence level in this discovery")


class Metric(BaseModel):
    """A computed metric value for a specific scope."""
    name: str = Field(..., description="Metric name (e.g., 'contrast_ratio')")
    scope_id: str = Field(..., description="Identifier for the scope this metric applies to")
    value: Union[float, int, str, bool, None] = Field(..., description="The metric value")
    unit: Optional[str] = Field(None, description="Unit of measurement if applicable")
    computed_from: List[FileSpan] = Field(..., description="Code spans used to compute this metric")
    notes: Optional[str] = Field(None, description="Additional notes about the computation")
    llm_model: str = Field(..., description="Model that computed this metric")


class ValidationDecision(BaseModel):
    """A validation decision made by LLM-3."""
    candidate_id: UUID = Field(..., description="ID of the candidate issue being validated")
    rule_id: str = Field(..., description="WCAG rule ID")
    passed: bool = Field(..., description="Whether the validation passed")
    severity: Severity = Field(..., description="Severity if validation failed")
    reasoning: str = Field(..., description="Explanation of the decision")
    metrics_used: Dict[str, Any] = Field(..., description="Metrics that were used in validation")
    llm_model: str = Field(..., description="Model that made this decision")


class FixSuggestion(BaseModel):
    """A fix suggestion generated by LLM-4."""
    candidate_id: UUID = Field(..., description="ID of the candidate issue being fixed")
    rule_id: str = Field(..., description="WCAG rule ID")
    patch_unified_diff: str = Field(..., description="Unified diff patch to apply")
    summary: str = Field(..., description="Brief summary of the fix")
    side_effects: List[str] = Field(default_factory=list, description="Potential side effects")
    test_suggestions: List[str] = Field(default_factory=list, description="Suggested tests")
    llm_model: str = Field(..., description="Model that generated this fix")


class FileContent(BaseModel):
    """Represents a file with its content."""
    path: str = Field(..., description="File path")
    content: str = Field(..., description="File content as string")


class ModelMap(BaseModel):
    """Configuration for which models to use in each stage."""
    model_config = {"protected_namespaces": ()}
    
    llm1: str = Field(..., description="Model for discovery stage")
    llm2: str = Field(..., description="Model for metrics stage")
    llm3: str = Field(..., description="Model for validation stage")
    llm4: str = Field(..., description="Model for fixes stage")


class PipelineRequest(BaseModel):
    """Request to run the accessibility pipeline."""
    session_id: str = Field(..., description="Session identifier")
    model_map: ModelMap = Field(..., description="Model configuration")
    files: List[FileContent] = Field(..., description="Files to analyze")


class PipelineTimings(BaseModel):
    """Timing information for each pipeline stage."""
    llm1_discovery_ms: Optional[int] = None
    llm2_metrics_ms: Optional[int] = None
    llm3_validation_ms: Optional[int] = None
    llm4_fixes_ms: Optional[int] = None
    total_ms: Optional[int] = None


class CostEstimate(BaseModel):
    """Cost estimation for the pipeline run."""
    llm1_tokens: Optional[int] = None
    llm2_tokens: Optional[int] = None
    llm3_tokens: Optional[int] = None
    llm4_tokens: Optional[int] = None
    total_estimated_cost_usd: Optional[float] = None


class PipelineResponse(BaseModel):
    """Response from the accessibility pipeline."""
    model_config = {"protected_namespaces": ()}
    
    session_id: str = Field(..., description="Session identifier")
    candidates: List[CandidateIssue] = Field(default_factory=list, description="Discovered issues")
    metrics: List[Metric] = Field(default_factory=list, description="Computed metrics")
    decisions: List[ValidationDecision] = Field(default_factory=list, description="Validation decisions")
    fixes: List[FixSuggestion] = Field(default_factory=list, description="Fix suggestions")
    timings: PipelineTimings = Field(..., description="Pipeline timing information")
    cost_estimate: CostEstimate = Field(..., description="Cost estimation")
    model_map_used: ModelMap = Field(..., description="Model configuration used")


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(default="ok", description="Health status")
    timestamp: str = Field(..., description="Current timestamp")


class UploadResponse(BaseModel):
    """Response from file upload endpoint."""
    session_id: str = Field(..., description="Session identifier")
    files_uploaded: int = Field(..., description="Number of files uploaded")
    file_manifest: List[str] = Field(..., description="List of uploaded file paths")
